(define
  (problem alignement-10dominos-7chiffres)
  (:domain alignement-dominos)
  (:requirements :strips :typing)
  (:objects
  c0 c1 c2 c3 c4 c5 c6 - number
  d0 d1 d2 d3 d4 d5 d6 d7 d8 d9 - domino
  )
  (:init
    (TableVide)
    (EnMain d0)
    (ChiffreGauche c4 d0)
    (ChiffreDroit c2 d0)
    (EnMain d1)
    (ChiffreGauche c5 d1)
    (ChiffreDroit c5 d1)
    (EnMain d2)
    (ChiffreGauche c6 d2)
    (ChiffreDroit c2 d2)
    (EnMain d3)
    (ChiffreGauche c0 d3)
    (ChiffreDroit c5 d3)
    (EnMain d4)
    (ChiffreGauche c4 d4)
    (ChiffreDroit c5 d4)
    (EnMain d5)
    (ChiffreGauche c3 d5)
    (ChiffreDroit c6 d5)
    (EnMain d6)
    (ChiffreGauche c5 d6)
    (ChiffreDroit c5 d6)
    (EnMain d7)
    (ChiffreGauche c5 d7)
    (ChiffreDroit c0 d7)
    (EnMain d8)
    (ChiffreGauche c6 d8)
    (ChiffreDroit c6 d8)
    (EnMain d9)
    (ChiffreGauche c3 d9)
    (ChiffreDroit c5 d9)
  )
  (:goal
    (and
      (not (EnMain d0))
      (not (EnMain d1))
      (not (EnMain d2))
      (not (EnMain d3))
      (not (EnMain d4))
      (not (EnMain d5))
      (not (EnMain d6))
      (not (EnMain d7))
      (not (EnMain d8))
      (not (EnMain d9))
    )
  )
)